### ISSUE TITLE
Default Branch?

### ISSUE THREAD

**Issue by joergboe** [IBMStreams/streamsx.sttgateway#18]
I think the default branch should be the master-branch.
All Pull-Requests should finally go into the master branch and not into the develop branch.

**Comment by schubon** [comment]
Hi Joerg,
when starting I configured it that way, because we once thought that we should mainly work in develop and pull new features over into master consciously.
I can easily change that, but GitHub then warns:

>> Changing your default branch can have unintended consequences that can affect new pull requests and clones.

So if you guys working on that repo keep that in the back of your minds and remember it, if you encounter something strange, I'll change that. Just give me another "Go" here, and it'll be done.

**Comment by schubon** [comment]
After exchange on Slack ...
... done
