### ISSUE TITLE
Re-Connect handling of WatsonSTT operator

### ISSUE THREAD

**Issue by joergboe** [IBMStreams/streamsx.sttgateway#28]
When the number of unsuccessful reaches the limit, the operator does not make any further attempts to connect to the stt service. This seems not to be very usefull.
For instance if there is an temporary network issue and the limit is reached, the operators will not make a re-connection.
I would propose, that the operator :
1) Still makes re-connection attemps, when the max. unsuccessful connection attempts limit is reached.
2) Slows down the the frequency of re-connection attempts, when the max. unsuccessful connection attempts limit is reached. (e.g. 1 attempt per minute)

**Comment by ghost** [comment]
The best thing, I think, is to do infinite reconnection retries with increasing delay starting with a minimum pause until a maximum pause is reached. The attempts can be counted in a metric in order to have a chance to see what happens inside the operator. After a  connection has been established, the delay is reset to the minimum delay and the metric (if there is one) is also reset. The delay can be hard-coded between something around some 100 ms and 60000 ms.

**Comment by ghost** [comment]
I think, there is no need to have **reconnectionPolicy** and **reconnectionBound** parameters like other toolkit operators have (I actually don't kown if the WatsonSTT operator already has them). Re-Launching PE's on long-lasting connection issues lead only to exceeded re-launch attempts (10) with finally failed PEs making the whole application stop working.

**Comment by joergboe** [comment]
I agree.
The operator defines 2 parameters:
- maxAllowedConnectionAttempts: which is the max. number of attempts with high frequency (default 10),
- waitTimeBeforeSTTServiceConnectionRetry: this is wait time for the next connection retry until the maxAllowedConnectionAttempts is reached (default 3 sec.)

I will now add the functionallity that the operator keeps trying to reach the stt service after maxAllowedConnectionAttempts with an (hard coded) period of 1 min. and the metric will be updated to reflect the current ce-connection counter (Counter reset after successful connection attempt)
